# Generated by Django 5.0 on 2024-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=150)),
                ('recipe_description', models.CharField(max_length=1000)),
                ('recipe_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
